const USER_CONNECTED = 'USER_CONNECTED';
const USER_CONNECTED_TRUE = 'USER_CONNECTED_TRUE';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const USER_VERIFY = 'USER_VERIFY';
const USER_TIMEOUT = 'USER_TIMEOUT';
const ADMIN_MESSAGE = 'ADMIN_MESSAGE';

const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
const MESSAGE_SENT = 'MESSAGE_SENT';
const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
const TYPING = 'TYPING';
const SET_USER_TYPING = 'SET_USER_TYPING';
const STOP_USER_TYPING = 'SET_USER_TYPING';

const SERVER_CONNECTED = 'SERVER_CONNECTED';
const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

const SERVER_ERROR = 'SERVER_ERROR';
const ERROR = 'ERROR';

const INIT_SOCKET = 'INIT_SOCKET';

module.exports = {
  INIT_SOCKET,
  USER_VERIFY,
  USER_CONNECTED,
  USER_DISCONNECTED,
  USER_TIMEOUT,
  TYPING,
  MESSAGE_SENT,
  MESSAGE_RECIEVED,
  ADMIN_MESSAGE,
  SERVER_CONNECTED,
  SERVER_DISCONNECTED,
  SERVER_ERROR,
  ERROR,
};
