export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const USER_VERIFY = 'USER_VERIFY';
export const USER_TIMEOUT = 'USER_TIMEOUT';

export const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const TYPING = 'TYPING';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const SERVER_ERROR = 'SERVER_ERROR';
export const ERROR = 'ERROR';

export const INIT_SOCKET = 'INIT_SOCKET';
